/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Commit;
import org.omg.sysml.model.Error;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommitApi
 */
@Ignore
public class CommitApiTest {

    private final CommitApi api = new CommitApi();

    
    /**
     * Get commit by project and ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommitByProjectAndIdTest() throws ApiException {
        UUID projectId = null;
        UUID commitId = null;
        Commit response = api.getCommitByProjectAndId(projectId, commitId);

        // TODO: test validations
    }
    
    /**
     * Get commits by project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommitsByProjectTest() throws ApiException {
        UUID projectId = null;
        String pageAfter = null;
        String pageBefore = null;
        Integer pageSize = null;
        List<Commit> response = api.getCommitsByProject(projectId, pageAfter, pageBefore, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create commit by project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCommitByProjectTest() throws ApiException {
        UUID projectId = null;
        Commit body = null;
        UUID branchId = null;
        Commit response = api.postCommitByProject(projectId, body, branchId);

        // TODO: test validations
    }
    
}
