/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Element;
import org.omg.sysml.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ElementApi
 */
@Ignore
public class ElementApiTest {

    private final ElementApi api = new ElementApi();

    
    /**
     * Add a new element
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createElementTest() throws ApiException {
        Map<String, Object> requestBody = null;
        Element response = api.createElement(requestBody);

        // TODO: test validations
    }
    
    /**
     * Get element by its ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getElementTest() throws ApiException {
        String identifier = null;
        Element response = api.getElement(identifier);

        // TODO: test validations
    }
    
    /**
     * Get element by project ID and its ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getElementByProjectAndIdTest() throws ApiException {
        String projectIdentifier = null;
        String elementIdentifier = null;
        Element response = api.getElementByProjectAndId(projectIdentifier, elementIdentifier);

        // TODO: test validations
    }
    
    /**
     * Get all elements
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getElementsTest() throws ApiException {
        List<Element> response = api.getElements();

        // TODO: test validations
    }
    
    /**
     * Get all elements in the project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getElementsInProjectTest() throws ApiException {
        String projectIdentifier = null;
        Element response = api.getElementsInProject(projectIdentifier);

        // TODO: test validations
    }
    
}
