/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Error;
import org.omg.sysml.model.Model;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModelApi
 */
@Ignore
public class ModelApiTest {

    private final ModelApi api = new ModelApi();

    
    /**
     * Add a new model
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createModelTest() throws ApiException {
        Model model = null;
        Model response = api.createModel(model);

        // TODO: test validations
    }
    
    /**
     * Get model by its ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getModelTest() throws ApiException {
        String id = null;
        Model response = api.getModel(id);

        // TODO: test validations
    }
    
    /**
     * Get all models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getModelsTest() throws ApiException {
        List<Model> response = api.getModels();

        // TODO: test validations
    }
    
}
