/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Error;
import org.omg.sysml.model.Project;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectApi
 */
@Ignore
public class ProjectApiTest {

    private final ProjectApi api = new ProjectApi();

    
    /**
     * Delete project by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectByIdTest() throws ApiException {
        UUID projectId = null;
        Project response = api.deleteProjectById(projectId);

        // TODO: test validations
    }
    
    /**
     * Get project by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectByIdTest() throws ApiException {
        UUID projectId = null;
        Project response = api.getProjectById(projectId);

        // TODO: test validations
    }
    
    /**
     * Get projects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectsTest() throws ApiException {
        String pageAfter = null;
        String pageBefore = null;
        Integer pageSize = null;
        List<Project> response = api.getProjects(pageAfter, pageBefore, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postProjectTest() throws ApiException {
        Project body = null;
        Project response = api.postProject(body);

        // TODO: test validations
    }
    
    /**
     * Update project by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putProjectByIdTest() throws ApiException {
        UUID projectId = null;
        Project body = null;
        Project response = api.putProjectById(projectId, body);

        // TODO: test validations
    }
    
}
