/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Error;
import org.omg.sysml.model.Relationship;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RelationshipApi
 */
@Ignore
public class RelationshipApiTest {

    private final RelationshipApi api = new RelationshipApi();

    
    /**
     * Get relationships by project, commit, and related element.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRelationshipsByProjectCommitRelatedElementTest() throws ApiException {
        UUID projectId = null;
        UUID commitId = null;
        UUID relatedElementId = null;
        String direction = null;
        List<Relationship> response = api.getRelationshipsByProjectCommitRelatedElement(projectId, commitId, relatedElementId, direction);

        // TODO: test validations
    }
    
}
