/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.api;

import org.omg.sysml.ApiException;
import org.omg.sysml.model.Branch;
import org.omg.sysml.model.Error;
import org.omg.sysml.model.Tag;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagApi
 */
@Ignore
public class TagApiTest {

    private final TagApi api = new TagApi();

    
    /**
     * Delete tag by project and ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTagByProjectAndIdTest() throws ApiException {
        UUID projectId = null;
        UUID tagId = null;
        Tag response = api.deleteTagByProjectAndId(projectId, tagId);

        // TODO: test validations
    }
    
    /**
     * Get tag by project and ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagByProjectAndIdTest() throws ApiException {
        UUID projectId = null;
        UUID tagId = null;
        Tag response = api.getTagByProjectAndId(projectId, tagId);

        // TODO: test validations
    }
    
    /**
     * Get tags by project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagsByProjectTest() throws ApiException {
        UUID projectId = null;
        String pageAfter = null;
        String pageBefore = null;
        Integer pageSize = null;
        List<Tag> response = api.getTagsByProject(projectId, pageAfter, pageBefore, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create tag by project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postTagByProjectTest() throws ApiException {
        UUID projectId = null;
        Tag body = null;
        Branch response = api.postTagByProject(projectId, body);

        // TODO: test validations
    }
    
}
