/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.omg.sysml.model.BranchHead;
import org.omg.sysml.model.BranchOwningProject;
import org.omg.sysml.model.DataVersion;

/**
 * Commit
 */

public class Commit {
  public static final String SERIALIZED_NAME_AT_ID = "@id";
  @SerializedName(SERIALIZED_NAME_AT_ID)
  private UUID atId;

  /**
   * Gets or Sets atType
   */
  @JsonAdapter(AtTypeEnum.Adapter.class)
  public enum AtTypeEnum {
    COMMIT("Commit");

    private String value;

    AtTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AtTypeEnum fromValue(String value) {
      for (AtTypeEnum b : AtTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AtTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AtTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AtTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AtTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AT_TYPE = "@type";
  @SerializedName(SERIALIZED_NAME_AT_TYPE)
  private AtTypeEnum atType;

  public static final String SERIALIZED_NAME_CHANGE = "change";
  @SerializedName(SERIALIZED_NAME_CHANGE)
  private List<DataVersion> change = null;

  public static final String SERIALIZED_NAME_OWNING_PROJECT = "owningProject";
  @SerializedName(SERIALIZED_NAME_OWNING_PROJECT)
  private BranchOwningProject owningProject;

  public static final String SERIALIZED_NAME_PREVIOUS_COMMIT = "previousCommit";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_COMMIT)
  private BranchHead previousCommit;


  public Commit atId(UUID atId) {
    
    this.atId = atId;
    return this;
  }

   /**
   * Get atId
   * @return atId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getAtId() {
    return atId;
  }


  public void setAtId(UUID atId) {
    this.atId = atId;
  }


  public Commit atType(AtTypeEnum atType) {
    
    this.atType = atType;
    return this;
  }

   /**
   * Get atType
   * @return atType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AtTypeEnum getAtType() {
    return atType;
  }


  public void setAtType(AtTypeEnum atType) {
    this.atType = atType;
  }


  public Commit change(List<DataVersion> change) {
    
    this.change = change;
    return this;
  }

  public Commit addChangeItem(DataVersion changeItem) {
    if (this.change == null) {
      this.change = new ArrayList<DataVersion>();
    }
    this.change.add(changeItem);
    return this;
  }

   /**
   * Get change
   * @return change
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DataVersion> getChange() {
    return change;
  }


  public void setChange(List<DataVersion> change) {
    this.change = change;
  }


  public Commit owningProject(BranchOwningProject owningProject) {
    
    this.owningProject = owningProject;
    return this;
  }

   /**
   * Get owningProject
   * @return owningProject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BranchOwningProject getOwningProject() {
    return owningProject;
  }


  public void setOwningProject(BranchOwningProject owningProject) {
    this.owningProject = owningProject;
  }


  public Commit previousCommit(BranchHead previousCommit) {
    
    this.previousCommit = previousCommit;
    return this;
  }

   /**
   * Get previousCommit
   * @return previousCommit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BranchHead getPreviousCommit() {
    return previousCommit;
  }


  public void setPreviousCommit(BranchHead previousCommit) {
    this.previousCommit = previousCommit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Commit commit = (Commit) o;
    return Objects.equals(this.atId, commit.atId) &&
        Objects.equals(this.atType, commit.atType) &&
        Objects.equals(this.change, commit.change) &&
        Objects.equals(this.owningProject, commit.owningProject) &&
        Objects.equals(this.previousCommit, commit.previousCommit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atId, atType, change, owningProject, previousCommit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Commit {\n");
    sb.append("    atId: ").append(toIndentedString(atId)).append("\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    owningProject: ").append(toIndentedString(owningProject)).append("\n");
    sb.append("    previousCommit: ").append(toIndentedString(previousCommit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

