/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.omg.sysml.model.BranchHead;
import org.omg.sysml.model.BranchOwningProject;
import org.threeten.bp.OffsetDateTime;

/**
 * Tag
 */

public class Tag {
  public static final String SERIALIZED_NAME_AT_ID = "@id";
  @SerializedName(SERIALIZED_NAME_AT_ID)
  private UUID atId;

  /**
   * Gets or Sets atType
   */
  @JsonAdapter(AtTypeEnum.Adapter.class)
  public enum AtTypeEnum {
    TAG("Tag");

    private String value;

    AtTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AtTypeEnum fromValue(String value) {
      for (AtTypeEnum b : AtTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AtTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AtTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AtTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AtTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AT_TYPE = "@type";
  @SerializedName(SERIALIZED_NAME_AT_TYPE)
  private AtTypeEnum atType;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OWNING_PROJECT = "owningProject";
  @SerializedName(SERIALIZED_NAME_OWNING_PROJECT)
  private BranchOwningProject owningProject;

  public static final String SERIALIZED_NAME_REFERENCED_COMMIT = "referencedCommit";
  @SerializedName(SERIALIZED_NAME_REFERENCED_COMMIT)
  private BranchHead referencedCommit;

  public static final String SERIALIZED_NAME_TAGGED_COMMIT = "taggedCommit";
  @SerializedName(SERIALIZED_NAME_TAGGED_COMMIT)
  private BranchHead taggedCommit;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;


  public Tag atId(UUID atId) {
    
    this.atId = atId;
    return this;
  }

   /**
   * Get atId
   * @return atId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getAtId() {
    return atId;
  }


  public void setAtId(UUID atId) {
    this.atId = atId;
  }


  public Tag atType(AtTypeEnum atType) {
    
    this.atType = atType;
    return this;
  }

   /**
   * Get atType
   * @return atType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AtTypeEnum getAtType() {
    return atType;
  }


  public void setAtType(AtTypeEnum atType) {
    this.atType = atType;
  }


  public Tag name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Tag owningProject(BranchOwningProject owningProject) {
    
    this.owningProject = owningProject;
    return this;
  }

   /**
   * Get owningProject
   * @return owningProject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BranchOwningProject getOwningProject() {
    return owningProject;
  }


  public void setOwningProject(BranchOwningProject owningProject) {
    this.owningProject = owningProject;
  }


  public Tag referencedCommit(BranchHead referencedCommit) {
    
    this.referencedCommit = referencedCommit;
    return this;
  }

   /**
   * Get referencedCommit
   * @return referencedCommit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BranchHead getReferencedCommit() {
    return referencedCommit;
  }


  public void setReferencedCommit(BranchHead referencedCommit) {
    this.referencedCommit = referencedCommit;
  }


  public Tag taggedCommit(BranchHead taggedCommit) {
    
    this.taggedCommit = taggedCommit;
    return this;
  }

   /**
   * Get taggedCommit
   * @return taggedCommit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BranchHead getTaggedCommit() {
    return taggedCommit;
  }


  public void setTaggedCommit(BranchHead taggedCommit) {
    this.taggedCommit = taggedCommit;
  }


  public Tag timestamp(OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag tag = (Tag) o;
    return Objects.equals(this.atId, tag.atId) &&
        Objects.equals(this.atType, tag.atType) &&
        Objects.equals(this.name, tag.name) &&
        Objects.equals(this.owningProject, tag.owningProject) &&
        Objects.equals(this.referencedCommit, tag.referencedCommit) &&
        Objects.equals(this.taggedCommit, tag.taggedCommit) &&
        Objects.equals(this.timestamp, tag.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atId, atType, name, owningProject, referencedCommit, taggedCommit, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag {\n");
    sb.append("    atId: ").append(toIndentedString(atId)).append("\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owningProject: ").append(toIndentedString(owningProject)).append("\n");
    sb.append("    referencedCommit: ").append(toIndentedString(referencedCommit)).append("\n");
    sb.append("    taggedCommit: ").append(toIndentedString(taggedCommit)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

