/*
 * SysML v2 API and Services
 * REST/HTTP binding (PSM) for the SysML v2 standard API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.omg.sysml.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PrimitiveConstraint
 */
public class PrimitiveConstraintTest {
    private final PrimitiveConstraint model = new PrimitiveConstraint();

    /**
     * Model tests for PrimitiveConstraint
     */
    @Test
    public void testPrimitiveConstraint() {
        // TODO: test PrimitiveConstraint
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'inverse'
     */
    @Test
    public void inverseTest() {
        // TODO: test inverse
    }

    /**
     * Test the property 'property'
     */
    @Test
    public void propertyTest() {
        // TODO: test property
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

}
